site_name: Fine-Tuning Methods Documentation
site_description: A technical reference for LoRA, QLoRA, and other fine-tuning techniques.
site_author: Saurabh Goyal
repo_url: https://github.com/saurabhiit2007/LLM-Finetuning
theme:
  name: material
  features:
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - mathjax
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: deep purple
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: lime
  font:
    text: Inter
    code: JetBrains Mono

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Speed:
      - Flash Attention: ./attention_optimization/flash_attention.md
      - Speculative Decoding: ./attention_optimization/speculative_decoding.md
      - vLLM: ./attention_optimization/vllm.md
  - Decoding:
      - Decoding Strategies: ./decoding_strategies/decoding_strategies.md
  - Memory:
      - KV Caching: ./memory/kv_caching.md



  - References: index.md

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
  - footnotes
  - tables
  - pymdownx.arithmatex
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.magiclink
